# Generated by Django 3.1.7 on 2021-03-12 10:33

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=24, verbose_name='エリア名')),
                ('SubName', models.CharField(max_length=24, verbose_name='サブタイトル')),
                ('Abstruct', models.TextField(max_length=256, verbose_name='概要')),
                ('Booklet', models.CharField(blank=True, max_length=24, null=True, verbose_name='収録冊子')),
                ('DEF_LAT', models.FloatField(default=34.6, verbose_name='中心緯度')),
                ('DEF_LON', models.FloatField(default=135.8, verbose_name='中心経度')),
                ('DEF_Zoom', models.IntegerField(default=15, verbose_name='ズームレベル')),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '1.マップエリア',
                'verbose_name_plural': '1.マップエリア',
            },
        ),
        migrations.CreateModel(
            name='Border',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n03_001', models.CharField(max_length=10, verbose_name='都道府県名')),
                ('n03_002', models.CharField(blank=True, max_length=20, verbose_name='支庁名')),
                ('n03_003', models.CharField(blank=True, max_length=20, verbose_name='群・政令市名')),
                ('n03_004', models.CharField(blank=True, max_length=20, verbose_name='市区町村名')),
                ('n03_007', models.CharField(max_length=5, verbose_name='行政区域コード')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
            options={
                'verbose_name': '行政区域',
                'verbose_name_plural': '行政区域一覧',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(1, 'gravel'), (2, 'difficulty'), (3, 'impassable'), (4, 'traffic')], default=1, verbose_name='ゾーンタイプ')),
                ('Name', models.CharField(max_length=24, verbose_name='名称')),
                ('Summery', models.CharField(max_length=256, null=True, verbose_name='概要')),
                ('Photo1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo1')),
                ('Photo2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo2')),
                ('Photo3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo3')),
                ('Photo360', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360')),
                ('Photo360_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360_2')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': '5.ゾーン情報',
                'verbose_name_plural': '5.ゾーン情報',
            },
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(100, 'toilet'), (999, 'etc')], default=100, verbose_name='地点タイプ')),
                ('Name', models.CharField(max_length=24, verbose_name='名称')),
                ('Summery', models.CharField(blank=True, max_length=256, null=True, verbose_name='概要')),
                ('Floor', models.CharField(blank=True, max_length=24, null=True, verbose_name='回数')),
                ('Babyseat', models.BooleanField(verbose_name='ベビーシート')),
                ('Ostomate', models.BooleanField(verbose_name='オストメイト')),
                ('Nursingbed', models.BooleanField(verbose_name='介護ベット')),
                ('Washlet', models.BooleanField(verbose_name='ウォシュレット')),
                ('Rotation', models.BooleanField(verbose_name='車いす転回')),
                ('Emergencycall', models.BooleanField(verbose_name='呼出ボタン')),
                ('Photo1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo1')),
                ('Photo2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo2')),
                ('Photo3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo3')),
                ('Photo360', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360')),
                ('Photo360_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360_2')),
                ('geom', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point([135.82, 34.68]), srid=4326)),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('AreaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': 'A1.トイレ情報',
                'verbose_name_plural': 'A1.トイレ情報',
            },
        ),
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(1, 'ゆるい坂'), (2, '中くらいの坂'), (3, '急な坂')], default=1, verbose_name='坂タイプ')),
                ('Name', models.CharField(max_length=24, verbose_name='名称')),
                ('Summery', models.CharField(blank=True, max_length=256, null=True, verbose_name='概要')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([135.82, 34.681], [135.83, 34.68]), srid=4326)),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': '4.ルート補足（坂）',
                'verbose_name_plural': '4.ルート補足（坂）',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(1, 'main'), (2, 'option')], default=1, verbose_name='ルート種類')),
                ('Name', models.CharField(max_length=24, verbose_name='名称')),
                ('Summery', models.CharField(blank=True, max_length=256, null=True, verbose_name='概要')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([135.82, 34.681], [135.83, 34.685]), srid=4326)),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': '2.推奨ルート',
                'verbose_name_plural': '2.推奨ルート',
            },
        ),
        migrations.CreateModel(
            name='PointData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(1, 'route'), (2, 'start'), (3, 'end'), (4, 'start_op'), (5, 'end_op'), (6, 'location'), (7, 'barrguide'), (8, 'attension'), (9, 'cation'), (10, 'busstop')], verbose_name='地点タイプ')),
                ('No', models.IntegerField(blank=True, null=True, verbose_name='地点番号')),
                ('Name', models.CharField(max_length=24, verbose_name='エリア名')),
                ('Summery', models.CharField(blank=True, max_length=256, null=True, verbose_name='概要')),
                ('Remarks', models.CharField(blank=True, max_length=256, null=True, verbose_name='備考')),
                ('Open', models.TimeField(blank=True, verbose_name='開始時刻')),
                ('Close', models.TimeField(blank=True, verbose_name='終了時刻')),
                ('OpeningNote', models.CharField(blank=True, max_length=256, verbose_name='時刻注釈')),
                ('Holiday', models.CharField(blank=True, max_length=256, verbose_name='休日')),
                ('Price', models.IntegerField(blank=True, verbose_name='価格')),
                ('PriceNote', models.CharField(blank=True, max_length=256, verbose_name='価格注釈')),
                ('Discount', models.CharField(blank=True, max_length=256, verbose_name='割引')),
                ('TEL', models.CharField(blank=True, max_length=16, verbose_name='電話番号')),
                ('URL', models.CharField(blank=True, max_length=256, verbose_name='URL')),
                ('Urltitle', models.CharField(blank=True, max_length=24, verbose_name='URL名称')),
                ('Photo1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo1')),
                ('Photo2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo2')),
                ('Photo3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo3')),
                ('Photo360', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360')),
                ('Photo360_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360_2')),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('geom', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point([135.82, 34.68]), srid=4326)),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': '3.地点情報',
                'verbose_name_plural': '3.地点情報',
            },
        ),
        migrations.CreateModel(
            name='ImageMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageMap', models.ImageField(null=True, upload_to='images/', verbose_name='イラスト地図')),
                ('LAT1', models.FloatField(verbose_name='左上緯度')),
                ('LON1', models.FloatField(verbose_name='左上経度')),
                ('LAT2', models.FloatField(verbose_name='右下緯度')),
                ('LON2', models.FloatField(verbose_name='右下経度')),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': '1.イメージマップ',
                'verbose_name_plural': '1.イメージマップ',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(101, 'hotel'), (999, 'etc')], default=101, verbose_name='地点タイプ')),
                ('Name', models.CharField(max_length=24, verbose_name='名称')),
                ('Summery', models.CharField(max_length=256, null=True, verbose_name='概要')),
                ('TEL', models.CharField(blank=True, max_length=24, null=True, verbose_name='電話')),
                ('Address', models.CharField(blank=True, max_length=256, null=True, verbose_name='住所')),
                ('Access', models.CharField(blank=True, max_length=256, null=True, verbose_name='アクセス')),
                ('URL', models.CharField(blank=True, max_length=256, null=True, verbose_name='URL')),
                ('URL_f21', models.CharField(blank=True, max_length=256, null=True, verbose_name='URL_F21')),
                ('Photo1', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo1')),
                ('Photo2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo2')),
                ('Photo3', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo3')),
                ('Photo360', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360')),
                ('Photo360_2', models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360_2')),
                ('geom', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point([135.82, 34.68]), srid=4326)),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('AreaId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': 'A2.ホテル情報',
                'verbose_name_plural': 'A2.ホテル情報',
            },
        ),
    ]
