# Generated by Django 3.1.7 on 2021-03-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32, verbose_name='エリア名')),
                ('SubName', models.CharField(max_length=256, verbose_name='タイトル')),
                ('Abstruct', models.CharField(max_length=256, verbose_name='概要')),
                ('Booklet', models.CharField(max_length=32, verbose_name='収録冊子')),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'エリア',
                'verbose_name_plural': 'エリア',
            },
        ),
        migrations.CreateModel(
            name='PointData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(1, 'route'), (2, 'start'), (3, 'end'), (4, 'start_op'), (5, 'end_op'), (6, 'location'), (7, 'barrguide'), (8, 'attension'), (9, 'cation'), (10, 'busstop')], verbose_name='地点タイプ')),
                ('No', models.IntegerField(verbose_name='地点番号')),
                ('Name', models.CharField(max_length=32, verbose_name='エリア名')),
                ('Summery', models.CharField(max_length=256, verbose_name='概要')),
                ('Remarks', models.CharField(max_length=256, verbose_name='備考')),
                ('Open', models.TimeField(verbose_name='開始時刻')),
                ('Close', models.TimeField(verbose_name='終了時刻')),
                ('OpeningNote', models.CharField(max_length=256, verbose_name='時刻注釈')),
                ('Holiday', models.CharField(max_length=256, verbose_name='休日')),
                ('Price', models.IntegerField(verbose_name='価格')),
                ('PriceNote', models.CharField(max_length=256, verbose_name='価格注釈')),
                ('Discount', models.CharField(max_length=256, verbose_name='割引')),
                ('Tel', models.CharField(max_length=16, verbose_name='電話番号')),
                ('Url', models.CharField(max_length=256, verbose_name='URL')),
                ('UrlTitle', models.CharField(max_length=32, verbose_name='URL名称')),
                ('Photo1', models.ImageField(upload_to='files/', verbose_name='画像１')),
                ('Photo2', models.ImageField(upload_to='files/', verbose_name='画像２')),
                ('Photo3', models.ImageField(upload_to='files/', verbose_name='画像３')),
                ('Photo360', models.ImageField(upload_to='files/', verbose_name='360度画像')),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
