# Generated by Django 3.1.7 on 2021-03-09 08:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0002_auto_20210309_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointdata',
            options={'verbose_name': '地点情報', 'verbose_name_plural': '地点情報'},
        ),
        migrations.AddField(
            model_name='pointdata',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo1',
            field=models.CharField(max_length=256, verbose_name='Photo1'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo2',
            field=models.CharField(max_length=256, verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo3',
            field=models.CharField(max_length=256, verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo360',
            field=models.CharField(max_length=256, verbose_name='Photo360'),
        ),
    ]
