# Generated by Django 3.1.7 on 2021-03-09 08:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0003_auto_20210309_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdata',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
