# Generated by Django 3.2.3 on 2021-07-14 09:51

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0003_delete_border'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '0.マップエリア', 'verbose_name_plural': '0.マップエリア'},
        ),
        migrations.AlterField(
            model_name='hotel',
            name='URL',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ホテルURL'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='URL_f21',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='紹介URL'),
        ),
        migrations.AlterField(
            model_name='route',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([135.82, 34.681], [135.83, 34.685]), srid=4326, verbose_name='ルート座標'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='AreaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID'),
        ),
    ]
