# Generated by Django 3.2.3 on 2021-07-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0004_auto_20210714_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'B.ホテル情報', 'verbose_name_plural': 'B.ホテル情報'},
        ),
        migrations.AlterModelOptions(
            name='toilet',
            options={'verbose_name': 'A.トイレ情報', 'verbose_name_plural': 'A.トイレ情報'},
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='AreaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Sort',
            field=models.IntegerField(choices=[(1, 'route'), (2, 'start'), (3, 'end'), (4, 'start_op'), (5, 'end_op'), (6, 'location'), (7, 'barrguide'), (8, 'attension'), (9, 'cation'), (10, 'busstop')], default=1, verbose_name='地点タイプ'),
        ),
    ]
