# Generated by Django 3.1.7 on 2021-03-10 06:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0004_auto_20210309_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointdata',
            name='Photo360_2',
            field=models.CharField(max_length=256, null=True, verbose_name='Photo360_2'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo360',
            field=models.CharField(max_length=256, null=True, verbose_name='Photo360'),
        ),
        migrations.CreateModel(
            name='Toilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(100, 'toilet'), (999, 'etc')], default=100, verbose_name='地点タイプ')),
                ('Name', models.CharField(max_length=32, verbose_name='名称')),
                ('Summery', models.CharField(max_length=256, null=True, verbose_name='概要')),
                ('Floor', models.CharField(max_length=32, verbose_name='回数')),
                ('Babyseat', models.BooleanField(verbose_name='ベビーシート')),
                ('Ostmate', models.BooleanField(verbose_name='オストメイト')),
                ('Nursingbed', models.BooleanField(verbose_name='介護ベット')),
                ('Washlet', models.BooleanField(verbose_name='ウォシュレット')),
                ('Rotation', models.BooleanField(verbose_name='車いす転回可')),
                ('Emagencycall', models.BooleanField(verbose_name='呼び出しボタン')),
                ('Photo1', models.CharField(max_length=256, null=True, verbose_name='Photo1')),
                ('Photo2', models.CharField(max_length=256, null=True, verbose_name='Photo2')),
                ('Photo3', models.CharField(max_length=256, null=True, verbose_name='Photo3')),
                ('Photo360', models.CharField(max_length=256, null=True, verbose_name='Photo360')),
                ('Photo360_2', models.CharField(max_length=256, null=True, verbose_name='Photo360_2')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': '地点情報',
                'verbose_name_plural': '地点情報',
            },
        ),
    ]
