# Generated by Django 3.1.7 on 2021-03-10 06:39

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.linestring
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0005_auto_20210310_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toilet',
            options={'verbose_name': 'トイレ情報', 'verbose_name_plural': 'トイレ情報'},
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point([135.82, 34.68]), srid=4326),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point([135.82, 34.68]), srid=4326),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sort', models.IntegerField(choices=[(1, 'ゆるい坂'), (2, '中くらいの坂'), (3, '急な坂')], default=1, verbose_name='坂タイプ')),
                ('Name', models.CharField(max_length=32, verbose_name='名称')),
                ('Summery', models.CharField(max_length=256, null=True, verbose_name='概要')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(default=django.contrib.gis.geos.linestring.LineString([135.82, 34.681], [135.83, 34.68]), srid=4326)),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': '推奨ルート',
                'verbose_name_plural': '推奨ルート',
            },
        ),
    ]
