# Generated by Django 3.2.3 on 2021-07-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0005_auto_20210715_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdata',
            name='Close',
            field=models.CharField(blank=True, max_length=256, verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Open',
            field=models.CharField(blank=True, max_length=256, verbose_name='開始時刻'),
        ),
    ]
