# Generated by Django 3.2.3 on 2021-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0006_auto_20210715_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdata',
            name='Price',
            field=models.CharField(blank=True, max_length=256, verbose_name='価格'),
        ),
    ]
