# Generated by Django 3.1.7 on 2021-03-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0007_auto_20210310_1558'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointdata',
            options={'verbose_name': '3.地点情報', 'verbose_name_plural': '3.地点情報'},
        ),
        migrations.AlterModelOptions(
            name='slope',
            options={'verbose_name': '4.ルート補足（坂）', 'verbose_name_plural': '4.ルート補足（坂）'},
        ),
        migrations.AlterField(
            model_name='area',
            name='Abstruct',
            field=models.TextField(max_length=256, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='area',
            name='SubName',
            field=models.CharField(max_length=32, verbose_name='タイトル'),
        ),
    ]
