# Generated by Django 3.1.7 on 2021-03-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0009_auto_20210310_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toilet',
            old_name='Emagencycall',
            new_name='Emargencycall',
        ),
    ]
