# Generated by Django 3.2.3 on 2021-07-16 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0009_alter_pointdata_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='AreaId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID'),
        ),
    ]
