# Generated by Django 3.2.3 on 2021-07-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0010_alter_route_areaid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '1.マップエリア', 'verbose_name_plural': '1.マップエリア'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'C.ホテル情報', 'verbose_name_plural': 'C.ホテル情報'},
        ),
        migrations.AlterModelOptions(
            name='imagemap',
            options={'verbose_name': '2.イラストマップ', 'verbose_name_plural': '2.イラストマップ'},
        ),
        migrations.AlterModelOptions(
            name='pointdata',
            options={'verbose_name': '4.ルート上の地点', 'verbose_name_plural': '4.ルート上の地点'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'verbose_name': '3.推奨ルート', 'verbose_name_plural': '3.推奨ルート'},
        ),
        migrations.AlterModelOptions(
            name='toilet',
            options={'verbose_name': 'B.トイレ情報', 'verbose_name_plural': 'B.トイレ情報'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'A.ゾーン情報', 'verbose_name_plural': 'A.ゾーン情報'},
        ),
        migrations.AlterField(
            model_name='route',
            name='Sort',
            field=models.IntegerField(choices=[(1, 'main'), (2, 'option'), (11, 'ゆるい坂'), (12, '中くらいの坂'), (13, '急な坂')], default=1, verbose_name='ルート種類'),
        ),
        migrations.DeleteModel(
            name='Slope',
        ),
    ]
