# Generated by Django 3.1.7 on 2021-03-10 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0011_auto_20210310_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='AreaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID'),
        ),
    ]
