# Generated by Django 3.2.3 on 2021-08-07 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0011_auto_20210716_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='Sort',
            field=models.IntegerField(choices=[(1, 'メインコース'), (2, 'オプション'), (11, 'ゆるい坂'), (12, '中くらいの坂'), (13, '急な坂')], default=1, verbose_name='ルート種類'),
        ),
    ]
