# Generated by Django 3.1.7 on 2021-03-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0012_auto_20210310_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Telephon',
        ),
        migrations.AddField(
            model_name='hotel',
            name='Telephone',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='area',
            name='Booklet',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='収録冊子'),
        ),
        migrations.AlterField(
            model_name='area',
            name='Name',
            field=models.CharField(max_length=24, verbose_name='エリア名'),
        ),
        migrations.AlterField(
            model_name='area',
            name='SubName',
            field=models.CharField(max_length=24, verbose_name='サブタイトル'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='住所'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Name',
            field=models.CharField(max_length=24, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Photo1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo1'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Photo2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Photo3',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Photo360',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Photo360_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360_2'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Url_F21',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='URL_F21'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Close',
            field=models.TimeField(blank=True, verbose_name='終了時刻'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Discount',
            field=models.CharField(blank=True, max_length=256, verbose_name='割引'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Holiday',
            field=models.CharField(blank=True, max_length=256, verbose_name='休日'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Name',
            field=models.CharField(max_length=24, verbose_name='エリア名'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='No',
            field=models.IntegerField(blank=True, null=True, verbose_name='地点番号'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Open',
            field=models.TimeField(blank=True, verbose_name='開始時刻'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='OpeningNote',
            field=models.CharField(blank=True, max_length=256, verbose_name='時刻注釈'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo1'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo3',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo360',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Photo360_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360_2'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Price',
            field=models.IntegerField(blank=True, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='PriceNote',
            field=models.CharField(blank=True, max_length=256, verbose_name='価格注釈'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Remarks',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Summery',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Tel',
            field=models.CharField(blank=True, max_length=16, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='Url',
            field=models.CharField(blank=True, max_length=256, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pointdata',
            name='UrlTitle',
            field=models.CharField(blank=True, max_length=24, verbose_name='URL名称'),
        ),
        migrations.AlterField(
            model_name='route',
            name='Name',
            field=models.CharField(max_length=24, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='route',
            name='Sort',
            field=models.IntegerField(choices=[(1, 'main'), (2, 'option')], default=1, verbose_name='ルート種類'),
        ),
        migrations.AlterField(
            model_name='route',
            name='Summery',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='slope',
            name='Name',
            field=models.CharField(max_length=24, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='slope',
            name='Summery',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Emergencycall',
            field=models.BooleanField(verbose_name='呼出ボタン'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Floor',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Name',
            field=models.CharField(max_length=24, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Photo1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo1'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Photo2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Photo3',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Photo360',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Photo360_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360_2'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Rotation',
            field=models.BooleanField(verbose_name='車いす転回'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Summery',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='概要'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='Name',
            field=models.CharField(max_length=24, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='Photo1',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo1'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='Photo2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='Photo3',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='Photo360',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='Photo360_2',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Photo360_2'),
        ),
    ]
