# Generated by Django 3.2.3 on 2021-08-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0012_alter_route_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='DisplayOrder',
            field=models.IntegerField(blank=True, null=True, verbose_name='表示順'),
        ),
    ]
