# Generated by Django 3.2.6 on 2021-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0013_area_displayorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=24, verbose_name='冊子名')),
                ('SubName', models.CharField(max_length=24, verbose_name='サブタイトル')),
                ('Abstruct', models.TextField(max_length=256, verbose_name='概要')),
                ('PDFfile', models.ImageField(null=True, upload_to='pdf/', verbose_name='PDFファイル')),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='発売時期')),
            ],
            options={
                'verbose_name': 'X.冊子リスト',
                'verbose_name_plural': 'X.冊子',
            },
        ),
    ]
