# Generated by Django 3.1.7 on 2021-03-11 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0013_auto_20210310_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='DEF_LAT',
            field=models.IntegerField(default=34.6, verbose_name='中心緯度'),
        ),
        migrations.AddField(
            model_name='area',
            name='DEF_LON',
            field=models.IntegerField(default=135.8, verbose_name='中心経度'),
        ),
        migrations.AddField(
            model_name='area',
            name='Zoom',
            field=models.IntegerField(default=15, verbose_name='ズームレベル'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='route',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='slope',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='zone',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.CreateModel(
            name='ImageMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=24, verbose_name='エリア名')),
                ('LAT1', models.IntegerField(verbose_name='左上緯度')),
                ('LON1', models.IntegerField(verbose_name='左上経度')),
                ('LAT2', models.IntegerField(verbose_name='右下緯度')),
                ('LON2', models.IntegerField(verbose_name='右下経度')),
                ('Timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時')),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID')),
            ],
            options={
                'verbose_name': '1.イメージマップ',
                'verbose_name_plural': '1.イメージマップ',
            },
        ),
    ]
