# Generated by Django 3.2.6 on 2021-08-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0014_booklet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklet',
            name='Timestamp',
        ),
        migrations.AddField(
            model_name='booklet',
            name='Publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='発売時期'),
        ),
    ]
