# Generated by Django 3.2.6 on 2021-08-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0015_auto_20210812_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='Publication',
            field=models.DateField(blank=True, null=True, verbose_name='発売時期'),
        ),
    ]
