# Generated by Django 3.1.7 on 2021-03-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0015_auto_20210311_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemap',
            name='LAT1',
            field=models.FloatField(verbose_name='左上緯度'),
        ),
        migrations.AlterField(
            model_name='imagemap',
            name='LAT2',
            field=models.FloatField(verbose_name='右下緯度'),
        ),
        migrations.AlterField(
            model_name='imagemap',
            name='LON1',
            field=models.FloatField(verbose_name='左上経度'),
        ),
        migrations.AlterField(
            model_name='imagemap',
            name='LON2',
            field=models.FloatField(verbose_name='右下経度'),
        ),
    ]
