# Generated by Django 3.2.6 on 2021-08-12 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0016_alter_booklet_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='PDFfile',
            field=models.FileField(upload_to='pdf/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='冊子PDF'),
        ),
    ]
