# Generated by Django 3.1.7 on 2021-03-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0016_auto_20210311_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='DEF_LAT',
            field=models.FloatField(default=34.6, verbose_name='中心緯度'),
        ),
        migrations.AlterField(
            model_name='area',
            name='DEF_LON',
            field=models.FloatField(default=135.8, verbose_name='中心経度'),
        ),
    ]
