# Generated by Django 3.2.6 on 2021-08-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0017_alter_booklet_pdffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklet',
            name='Abstruct',
        ),
        migrations.AddField(
            model_name='booklet',
            name='Remarks',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='備考'),
        ),
    ]
