# Generated by Django 3.2.6 on 2021-08-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0018_auto_20210812_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklet',
            name='SubName',
            field=models.CharField(max_length=32, verbose_name='サブタイトル'),
        ),
    ]
