# Generated by Django 3.2.6 on 2021-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0021_area_displayflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilet',
            name='Babyseat',
            field=models.BooleanField(default=False, verbose_name='ベビーシート'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Emergencycall',
            field=models.BooleanField(default=False, verbose_name='呼出ボタン'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Nursingbed',
            field=models.BooleanField(default=False, verbose_name='介護ベット'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Ostomate',
            field=models.BooleanField(default=False, verbose_name='オストメイト'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Rotation',
            field=models.BooleanField(default=False, verbose_name='車いす転回'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Washlet',
            field=models.BooleanField(default=False, verbose_name='ウォシュレット'),
        ),
    ]
