# Generated by Django 3.2.6 on 2021-08-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0023_alter_pointdata_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointdata',
            name='Sort',
            field=models.IntegerField(choices=[(1, 'route'), (12, 'option'), (2, 'start'), (3, 'end'), (4, 'start_op'), (5, 'end_op'), (7, 'barrguide'), (14, 'roadguide'), (8, 'attension'), (9, 'caution'), (6, 'location'), (10, 'busstop'), (11, 'shop'), (13, 'restaurant')], default=1, verbose_name='地点タイプ'),
        ),
    ]
