# Generated by Django 3.2.6 on 2021-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0025_alter_pointdata_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Babyseat',
            field=models.BooleanField(default=False, verbose_name='ベビーシート'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Bath',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='大浴場'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='BreakfastArrange',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='食事アレンジ'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='BreakfastPlace',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='朝食会場'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Emergencycall',
            field=models.BooleanField(default=False, verbose_name='呼出ボタン'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Image1',
            field=models.ImageField(null=True, upload_to='photos/hotel/', verbose_name='画像１'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Image2',
            field=models.ImageField(null=True, upload_to='photos/hotel/', verbose_name='画像２'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ImageAdd1',
            field=models.ImageField(null=True, upload_to='photos/hotel/', verbose_name='追加画像１'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ImageAdd2',
            field=models.ImageField(null=True, upload_to='photos/hotel/', verbose_name='追加画像２'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Moving',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='客室への移動'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Nursingbed',
            field=models.BooleanField(default=False, verbose_name='介護ベット'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Ostomate',
            field=models.BooleanField(default=False, verbose_name='オストメイト'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Parking',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='駐車場'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Rental',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='貸出し備品'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomBabyseat',
            field=models.BooleanField(default=False, verbose_name='ベビーシート'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomBath',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='室内浴室'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomName',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='ルーム名'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomNursingbed',
            field=models.BooleanField(default=False, verbose_name='介護ベット'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomOstomate',
            field=models.BooleanField(default=False, verbose_name='オストメイト'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomPrice',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='価格'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomRotation',
            field=models.BooleanField(default=False, verbose_name='車いす転回'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomSize',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='室内広さ'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomToilet',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='室内トイレ'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='RoomWashlet',
            field=models.BooleanField(default=False, verbose_name='ウォシュレット'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Rotation',
            field=models.BooleanField(default=False, verbose_name='車いす転回'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Staff',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='スタッフ補助'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Toilet',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='多目的トイレ'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Washlet',
            field=models.BooleanField(default=False, verbose_name='ウォシュレット'),
        ),
    ]
