# Generated by Django 3.2.6 on 2021-09-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0026_auto_20210906_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='RoomEmergencycall',
            field=models.BooleanField(default=False, verbose_name='呼出ボタン'),
        ),
    ]
