# Generated by Django 3.2.6 on 2021-09-06 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0027_hotel_roomemergencycall'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Remarks',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='AreaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unimap.area', verbose_name='エリアID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/hotel/', verbose_name='画像１'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/hotel/', verbose_name='画像２'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='ImageAdd1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/hotel/', verbose_name='追加画像１'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='ImageAdd2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/hotel/', verbose_name='追加画像２'),
        ),
    ]
