# Generated by Django 3.2.6 on 2021-09-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0029_auto_20210907_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Photo360bath',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='浴室画像360URL'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Photo360toilet',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='トイレ画像360URL'),
        ),
    ]
