# Generated by Django 3.2.6 on 2021-09-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0030_auto_20210907_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='URL_f21',
        ),
    ]
