# Generated by Django 3.2.6 on 2021-09-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0031_remove_hotel_url_f21'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Checkin',
            field=models.TimeField(blank=True, null=True, verbose_name='チェックイン'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='Checkout',
            field=models.TimeField(blank=True, null=True, verbose_name='チェックアウト'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ToiletFloor',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='トイレ回数'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='TEL',
            field=models.CharField(default=0, max_length=24, verbose_name='電話'),
        ),
    ]
