# Generated by Django 3.2.6 on 2021-09-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0032_auto_20210907_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Sort',
        ),
    ]
