# Generated by Django 3.2.6 on 2021-09-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0033_remove_hotel_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='ToiletFloor',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='トイレ階数'),
        ),
        migrations.AlterField(
            model_name='toilet',
            name='Floor',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='階数'),
        ),
    ]
