# Generated by Django 3.2.6 on 2021-09-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0035_auto_20210907_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='toilet',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/toilet/', verbose_name='画像１'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/toilet/', verbose_name='画像２'),
        ),
        migrations.AddField(
            model_name='toilet',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/toilet/', verbose_name='画像３'),
        ),
    ]
