# Generated by Django 3.2.6 on 2021-09-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0036_auto_20210916_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toilet',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='Photo3',
        ),
        migrations.RemoveField(
            model_name='toilet',
            name='Photo360_2',
        ),
    ]
