# Generated by Django 3.2.6 on 2021-09-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0037_auto_20210916_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='Photo3',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='Photo360_2',
        ),
        migrations.AddField(
            model_name='pointdata',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/point/', verbose_name='画像１'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='Image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/point/', verbose_name='画像２'),
        ),
        migrations.AddField(
            model_name='pointdata',
            name='Image3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/point/', verbose_name='画像３'),
        ),
    ]
