# Generated by Django 3.2.3 on 2022-03-16 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0038_auto_20210916_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointdata',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='pointdata',
            name='Photo3',
        ),
        migrations.RemoveField(
            model_name='pointdata',
            name='Photo360_2',
        ),
    ]
