# Generated by Django 3.2.12 on 2022-03-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unimap', '0039_auto_20220316_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='AreaSort',
            field=models.IntegerField(choices=[(1, 'エリア'), (2, 'コース')], default=1, verbose_name='マップタイプ'),
        ),
    ]
